version: '3.8'

services:
  # Aplicación principal
  app:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - .:/app  # Montar todo el proyecto para desarrollo
      - /app/__pycache__  # Evitar conflictos de cache
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped
    depends_on:
      - mongodb

  # Base de datos MongoDB para datos y modelos
  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    restart: unless-stopped

volumes:
  mongodb_data:
