# Docker Compose para EcoPrint AI
# Sistema de Predicción de Riesgo de Incendios Forestales

services:
  # ===========================================
  # API Backend
  # ===========================================
  ecoprint-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecoprint-api
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=${MONGO_URI}
      - DB_NAME=${DB_NAME:-ensemble_models}
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    volumes:
      - ./models:/app/models:ro  # Solo lectura para los modelos
      - ./logs:/app/logs         # Logs de la aplicación
    # depends_on:
    #   - mongo  # Comentado porque MongoDB es opcional
    restart: unless-stopped
    networks:
      - ecoprint-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # ===========================================
  # MongoDB (Opcional - para desarrollo local)
  # ===========================================
  mongo:
    image: mongo:7.0
    container_name: ecoprint-mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password123
      - MONGO_INITDB_DATABASE=ensemble_models
    volumes:
      - mongo_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d:ro
    restart: unless-stopped
    networks:
      - ecoprint-network
    profiles:
      - local-db  # Solo se ejecuta con --profile local-db

  # ===========================================
  # MongoDB Express (Opcional - para administración)
  # ===========================================
  mongo-express:
    image: mongo-express:1.0.0
    container_name: ecoprint-mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password123
      - ME_CONFIG_MONGODB_URL=mongodb://admin:password123@mongo:27017/
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin123
    depends_on:
      - mongo
    restart: unless-stopped
    networks:
      - ecoprint-network
    profiles:
      - local-db  # Solo se ejecuta con --profile local-db

# ===========================================
# Volúmenes
# ===========================================
volumes:
  mongo_data:
    driver: local

# ===========================================
# Redes
# ===========================================
networks:
  ecoprint-network:
    driver: bridge
