services:
  - type: web
    name: fireriskai-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MONGO_URI
        sync: false
      - key: WEATHER_API_KEY
        sync: false
      - key: DB_NAME
        value: ensemble_models
      - key: APP_PORT
        value: 8000
      - key: LOG_LEVEL
        value: INFO
